# Generated by Django 3.2.5 on 2022-10-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 43, 15, 491955)),
        ),
    ]
