# Generated by Django 3.2.5 on 2022-10-17 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_auto_20221004_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 18, 18, 38, 891092)),
        ),
    ]
